version: '3.1'

services:
    mysql:
        image: mysql
        container_name: mysql_survey
        volumes:
            - "/var/data/mysql_survey:/var/lib/mysql_survey"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "3306:3306"
